chunking:
  chunk_size: 150
  overlap: 30

data:
  input_path: "data/raw/"

embedding:
  model_name: BAAI/bge-base-en


generation:
  model_name: gpt-4o-mini
  temperature: 0.2


retrieval:
  top_k: 5
  reranker_model: cross-encoder/ms-marco-MiniLM-L-6-v2